import { Nunito_Sans, Lato, Kalam, Lexend_Deca } from 'next/font/google';

import Navbar from '@/layouts/Navbar';
import './globals.css';

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-nunito',
  display: 'swap',
});

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  variable: '--font-lexend-deca',
  display: 'swap',
});

const lato = Lato({
  subsets: ['latin'],
  variable: '--font-lato',
  display: 'swap',
  weight: ['300', '400', '700', '900'],
});

const kalam = Kalam({
  subsets: ['latin'],
  variable: '--font-kalam',
  display: 'swap',
  weight: ['400', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang='en'
      data-theme='lofi'
      className={`${nunitoSans.variable} ${lato.variable} ${kalam.variable} ${lexendDeca.variable}`}
    >
      <body className='bg-neutral-20 relative min-h-[100vh] overflow-x-hidden'>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
