import Head from 'next/head';
import Navbar from '@/layouts/Navbar';
import './globals.css';
import { Nunito_Sans, Lato, Kalam } from 'next/font/google';

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-nunito',
  display: 'swap',
  // fallback: [
  //   "Nunito Sans",
  //   "system-ui",
  //   "-apple-system",
  //   "Segoe UI",
  //   "Roboto",
  //   "Oxygen",
  //   "Ubuntu",
  //   "Helvetica Neue",
  //   "sans-serif",
  // ],
});

const lato = Lato({
  subsets: ['latin'],
  variable: '--font-lato',
  display: 'swap',
  weight: ['300', '400', '700', '900'],
});

const kalam = Kalam({
  subsets: ['latin'],
  variable: '--font-kalam',
  display: 'swap',
  weight: ['400', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang='en'
      className={`${nunitoSans.variable} ${lato.variable} ${kalam.variable}`}
    >
      <Head>
        <meta name='viewport' minimum-scale='1.0'/>
      </Head>
      <body className='relative min-h-[100vh] overflow-x-hidden bg-neutral-20'>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
